name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known_hosts
        run: ssh-keyscan -H 103.94.239.197 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh dekas19@103.94.239.197 "cd /var/www/portal-cbt && \
            sudo chown -R dekas19:dekas19 storage bootstrap/cache && \
            git pull origin main && \
            composer install --no-dev --no-interaction && \
            php artisan migrate --force && \
            php artisan optimize:clear && \
            sudo chown -R www-data:www-data storage bootstrap/cache && \
            sudo chmod -R 775 storage bootstrap/cache"
